### ISSUE TITLE
Lots of PTRACE_GETREGSET: No such device in debugging seance in radare2

### ISSUE THREAD

**Issue by fr0ster** [radareorg/radare2#17919]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25261 @ linux-x86-64 git.4.4.0-925-g14f82ee30
commit: 14f82ee3012e10b56674a01c360ac1fbc4b4bf52 build: 2020-11-13__14:41:05

### Expected behavior

$ r2 -d r4j/bin/rshell
Process with PID 18104 started...
= attach 18104 18104
bin.baddr 0x564f7749f000
Using 0x564f7749f000
asm.bits 64
 -- I nodejs so hard my exams. What a nodejs!
[0x7f6e53e64090]>

### Actual behavior

$ r2 -d r4j/bin/rshell
Process with PID 18104 started...
= attach 18104 18104
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
bin.baddr 0x564f7749f000
Using 0x564f7749f000
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
asm.bits 64
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
 -- I nodejs so hard my exams. What a nodejs!
[0x7f6e53e64090]>

### Steps to reproduce the behavior 
Just start debugging any binary

r2 -d /bin/ls                                                                                                                                     vagrant@kali
Process with PID 161438 started...
= attach 161438 161438
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
bin.baddr 0x55e679070000
Using 0x55e679070000
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
asm.bits 64
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
 -- What about taking a break? Here, have this nice 0xCC.
[0x7f0579361090]>

### Additional Logs, screenshots, source-code,  configuration dump, ...
https://asciinema.org/a/372915

**Comment by 9Demien9** [comment]
Hello!
radare2 is installed on two computers, at work and at home. On a working computer after the last two updates, "PTRACE_GETREGS: No such device" no longer issues. At home, the problem remains. 
System on both: archlinux x86_64
I am not a good IT specialist, but  some  logs/files/parameters things I can look at. 
I would like that "PTRACE_GETREGS: No such device" would not occur anywhere. 
Ask, I'll try to answer.

**Comment by trufae** [comment]
I'm aware of those issues were introduced about 1 year ago, also the r2 debugger is also completely broken (not even able to spawn) on musl systems like alpine linux, all this got broken like 1 year ago. Guess its time to fix

**Comment by trufae** [comment]
![Screenshot 2021-04-14 at 10 39 47](https://user-images.githubusercontent.com/6431515/114680763-c890ca80-9d0d-11eb-8872-5e1b822c3f66.png)

**Comment by trufae** [comment]
On linux-arm64

![96881114-82B1-4340-A285-D1193E39E551](https://user-images.githubusercontent.com/6431515/114681389-66849500-9d0e-11eb-8187-afac6d972bc7.jpeg)

**Comment by trufae** [comment]
This is also another bug in the linux debugger, probably related to the ptrace-wrap code https://github.com/radareorg/radare2/issues/18525

**Comment by trufae** [comment]
Btw debian 4 is... debian etch? thats from 2007.. i guess some ptrace apis changed and we need to do some ifdefs around. would be nice to determine which commit broke that

**Comment by LightningsFury** [comment]
I'm on Manjaro and getting lots of this `PTRACE_GETREGSET: No such device` error doing anything on debug mode on Radare2. 
Upon running `r2 -d somebinary` I get:
```
Process with PID 99990 started...
= attach 99990 99990
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
bin.baddr 0x55effb408000
Using 0x55effb408000
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
asm.bits 64
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
 -- r2 -- leading options since 2006
```

And with moving around in visual mode, the screen glitches out when scrolling with the error momentarily popping up, especially prominent in the `!` screen where the scrolling seems dysfunctional. Running code with breakpoints seems to throw this error a lot, but **usually** works as it should, but I'm not an advanced user since I only started learning radare2 yesterday. I'm not sure whether this is connected, but my debugging sessions randomly break with obscure errors such that I need to restart r2. My use cases are basic reverse engineering like what I'd do with gdb.

**Comment by heinosasshallik** [comment]
I'm getting the same error

```
Process with PID 21265 started...
= attach 21265 21265
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
bin.baddr 0x560eee31b000
Using 0x560eee31b000
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
asm.bits 64
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
 -- This binary no good. Try another.
[0x7f9655f2e090]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)

```

**Comment by trufae** [comment]
another referenced issue to this https://github.com/radareorg/radare2/issues/17278#issuecomment-660787516

**Comment by trufae** [comment]
The "No such device" issue should be fixed in master now. can you please retry to confirm?

**Comment by 9Demien9** [comment]
YES! "PTRACE_GETREGSET: No such device" not anymore. You are the best! Thank you very much!!!

**Comment by AlbinoShadow** [comment]
Resolved for me as well.

**Comment by trufae** [comment]
Lets close this issue and reopen the alpine one

**Comment by maelray123** [comment]
I'm on kali linux and I still get that issue. I downloaded radare2 from the kali repo

**Comment by hollohan** [comment]
@maelray123 I had the same issue on kali.  Clone this repo to install rather than using apt.
