### ISSUE TITLE
Snow mode undoes the ANSI codes for colors

### ISSUE THREAD

**Issue by rouanth** [radareorg/radare2#19440]
## Environment

```sh
Wed Nov 24 05:42:17 PM MSK 2021
radare2 5.4.2 0 @ linux-x86-64 git.5.4.2
commit: unknown build: 2021-10-01__17:48:03
Linux x86_64
```

## Description

The color of the text to the right of the snowflake are reset to white, until the next color switch.

## Test

1. Enter the panels mode.
2. Press `(`.
3. Observe the colors flashing.

![20211124_17h44m22s_grim](https://user-images.githubusercontent.com/15677651/143259516-3995f88f-1cff-4cf5-b443-5bebc3af66ee.png)

**Comment by trufae** [comment]
This is somewhat fixed in master. Check it out and close the issue if the new behaviour works for you

**Comment by giantbranch** [comment]
@trufae Hello, pancake. I sent you two emails more than a week ago. Did you receive them?

**Comment by trufae** [comment]
Yep i did and i answer them :?

**Comment by giantbranch** [comment]
One of them is a reply to your email on November 17, 2021, and the other is titled "5 new security issues in radare2".

I have just resent this two emails. You can check the mailbox. (Your email is still pancake@nopcode.org？)

**Comment by rouanth** [comment]
Not really sure what changed, the issue seems to be still present in 7c20ef7f2aa6e08e2dadc6e74131b0f1f870586e.
![20211129_18h06m22s_grim](https://user-images.githubusercontent.com/15677651/143892711-7adfc643-d03b-438e-9b14-b5ed7c5889f5.png)
For example, see the `xor` changing its color mid-word on the first line of the disassembly, or the offset on the second line.

**Comment by trufae** [comment]
This cant be the commit you mention because its actually showing snow not magenta sakura. And yep this issues were fixed in master

**Comment by rouanth** [comment]
Ah, yeah, sorry. I attempted to check this by only building the project and running `binr/radare2/radare2`, but it seems like I needed to properly install it as well.

The problem is much less pronounced now. Occasionally, colors still break, but very rarely.

![20211130_10h36m17s_grim](https://user-images.githubusercontent.com/15677651/144005328-62b32358-efeb-4c2c-88c4-631ee27d6b3d.png)
