### ISSUE TITLE
-nn mode automatic functions detection

### ISSUE THREAD

**Issue by VPaulV** [radareorg/radare2#5289]
Would be nice if r2 could detect functions and build call graph when binary is loaded in the bare mode.

It is useful for working with memory dumps.

For example, IDAPro provides [the following call graph](http://pastebin.com/3X9Vmu1c) for 5a5fb377785855488f45a8fd8f6e089eaf9bdeda34712958bc038594326d2b72_dump_0x00400000 when dump is loaded as "Binary file"

[citadel_d__0x00400000.zip - password: infected](https://github.com/radare/radare2/files/269349/citadel_d__0x00400000.zip)

**Comment by radare** [comment]
there’s nothing to stop r2 to analyze binaries without interpretting the binary header. you can even analize the header from memory or run the analysis in the offsets you want

**Comment by Maijin** [comment]
Well aap: `Analyzed 0 functions based on preludes`
aac: `cur binfile null`

**Comment by VPaulV** [comment]
If I load citadel_dump not in bare mode with:
```
r2 dump -m 0x00400000 
aaa(or aaaa)
[0x004304d5]> afl~?
555
agc $$
```
The agc output will be just:
```
digraph code {
	graph [bgcolor=white fontname="Courier"];
	node [color=gray, style=filled shape=box];
	edge [arrowhead="vee"];
	"0x004304d5" -> "0x00413d60" [label="fcn.00413d60" color="green" URL="fcn.00413d60/0x00413d60"];
	"0x00413d60" [label="fcn.00413d60" URL="fcn.00413d60/0x00413d60"];
}
```

**Comment by radare** [comment]
i see several problems here:

* r2 is posix. so you can't pass commandline flags after the file . if you do, r2 will try to open `-m` and `0x00.. `as files
* why are you remapping the binary to 0x40000 ? r2 dump already works fine
* if you want a callgraph just use `aac`. no need for any other analysis to be performend which results in 798 functions instead of 555)
* agc -1 > a.dot works as expected. see:
<img width="761" alt="screen shot 2016-07-05 at 15 44 24" src="https://cloud.githubusercontent.com/assets/917142/16586682/673c39ae-42c7-11e6-9383-cfef47835404.png">

**Comment by VPaulV** [comment]
Didn't know about agc -1, thought that I should do it with agc $$. Thank you.

About 798 functions instead of 555 - you have old r2 version

**Comment by Maijin** [comment]
Is this fixing your issue ?

**Comment by radare** [comment]
agc $$ only show callgraph of given function

i doubt i have an old r2 :P maybe thats you


**Comment by VPaulV** [comment]
> why are you remapping the binary to 0x40000 ? r2 dump already works fine
Just to get more precise results

r2 -m 0x00400000 ~/MasterThesis/malware/citadel/dump_0x00400000
```
[0x004304d5]> aac
[0x004304d5]> afl~?
554
[0x004304d5]> 
```
vs
r2 ~/MasterThesis/malware/citadel/dump_0x00400000
```
[0x004304d5]> aac
[0x004304d5]> afl~?
521
[0x004304d5]>
```

Yes, I think the issue is solved then. Thank you

**Comment by radare** [comment]
the -1 thing is not documented i think.. the help message should be updated or make this available on agC to make it clear that it is not a function callgraph, but program one. what makes more sense to you?

**Comment by radare** [comment]
done. see ag? for help

**Comment by zonkzonk** [comment]
morrn, here is quick idea, wat about using afl for the afl fuzzer as builtin?

**Comment by radare** [comment]
this idea seems interesting but totally unrelated to this issue, please open another issue for this

**Comment by VPaulV** [comment]
Hi, I just realised that this issue is still exists.

Now I really need to load samples in the bare mode without parsing PE structure, because in the normal mode after `-B` r2  wrongly rebasing the code section a second time and all functions addresses a shifted for 0xC00 in comparison with the ground truth.

So the problem is still exist, when sample is loaded in `-nn` mode, r2 is not able to find functions.

**Comment by Maijin** [comment]
Ok so Sf should be run by default on -nn then

**Comment by radare** [comment]
its only required for analysis right?

i would not add this with -n, but maybe with -nn makes sense for now

**Comment by Maijin** [comment]
It's for `-nn` yep for analysis.

**Comment by radare** [comment]
lgtm, any other concern?

**Comment by Maijin** [comment]
ok this should fix aap but won't fix aac `cur binfile null`
